src/Entity/Rendezvous.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RendezvousRepository")
 */
class Rendezvous
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Docteur", inversedBy="rendezvouses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Docteur;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $disponible;

    public function __construct()
    {
        $this->disponible = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDocteur(): ?Docteur
    {
        return $this->Docteur;
    }

    public function setDocteur(?Docteur $Docteur): self
    {
        $this->Docteur = $Docteur;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDisponibile(): ?bool
    {
        return $this->disponible;
    }

    public function setDisponibile(bool $disponible): self
    {
        $this->ouvert = $disponible;

        return $this;
    }
}

templates/components/menu.html.twig
<ul class="list">
            {# <li class="header">MAIN NAVIGATION</li> #}
            <li class="active">
                <a href="{{ path('home') }}">
                    <i class="material-icons">home</i>
                    <span>{{ 'action.home.title'|trans }}</span>
                </a>
            </li>
            <li>
                <a href="{{ path('docteur_index') }}">
                    <i class="material-icons">domain</i>
                    <span>{{ 'action.docteur.title'|trans }}</span>
                </a>
            </li>
            <li>
                <a href="{{ path('pharmacie_index') }}">
                    <i class="material-icons">local_pharmacy</i>
                    <span>{{ 'action.pharmacie.title'|trans }}</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons">local_hospital</i>
                    <span>{{ 'action.medicament.title'|trans }}</span>
                </a>
                <ul class="ml-menu">
                    <li>
                        <a href="{{ path('medicament_index') }}">
                            <i class="material-icons">subject</i>
                            <span>{{ 'action.medicament.title'|trans }}</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">settings</i>
                            <span>{{ 'action.medicament.configuration.title'|trans }}</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a href="{{ path('laboratoire_index') }}">{{ 'action.medicament.configuration.laboratoire'|trans }}</a>
                            </li>
                            <li>
                                <a href="{{ path('code_atc_index') }}">{{ 'action.medicament.configuration.code_atc'|trans }}</a>
                            </li>
                            <li>
                                <a href="{{ path('pathologie_index') }}">{{ 'action.medicament.configuration.pathologie'|trans }}</a>
                            </li>
                            <li>
                                <a href="{{ path('principes_actifs_index') }}">{{ 'action.medicament.configuration.principe_actif'|trans }}</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{{ path('astuces_index') }}">
                    <i class="material-icons">beenhere</i>
                    <span>{{ 'action.astuces.title'|trans }}</span>
                </a>
            </li>
        </ul>

templates/components/scripts.html.twig
<!-- Jquery Core Js -->
        <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>        
        <!-- Bootstrap Core Js -->
        <script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.js') }}"></script>
        <!-- Select Plugin Js -->
        <script src="{{ asset('assets/plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>
        <!-- Slimscroll Plugin Js -->
        <script src="{{ asset('assets/plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>
        <!-- Waves Effect Plugin Js -->
        <script src="{{ asset('assets/plugins/node-waves/waves.js') }}"></script>
        <!-- Jquery CountTo Plugin Js -->
        <script src="{{ asset('assets/plugins/jquery-countto/jquery.countTo.js') }}"></script>
        <!-- Morris Plugin Js -->
        <script src="{{ asset('assets/plugins/raphael/raphael.min.js') }}"></script>        
        <script src="{{ asset('assets/plugins/morrisjs/morris.js') }}"></script>
        <!-- ChartJs -->
        <script src="{{ asset('assets/plugins/chartjs/Chart.bundle.js') }}"></script>
        <!-- Flot Charts Plugin Js -->
        <script src="{{ asset('assets/plugins/flot-charts/jquery.flot.js') }}"></script>        
        <script src="{{ asset('assets/plugins/flot-charts/jquery.flot.resize.js') }}"></script>        
        <script src="{{ asset('assets/plugins/flot-charts/jquery.flot.pie.js') }}"></script>        
        <script src="{{ asset('assets/plugins/flot-charts/jquery.flot.categories.js') }}"></script>        
        <script src="{{ asset('assets/plugins/flot-charts/jquery.flot.time.js') }}"></script>
        <!-- Sparkline Chart Plugin Js -->
        <script src="{{ asset('assets/plugins/jquery-sparkline/jquery.sparkline.js') }}"></script>
        <!-- Custom Js -->
        <script src="{{ asset('assets/js/admin.js') }}"></script>        
        <script src="{{ asset('assets/js/pages/index.js') }}"></script>
        <!-- Demo Js -->
        <script src="{{ asset('assets/js/demo.js') }}"></script>   

templates/components/styles.html.twig
<!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Css -->
        <link href="{{ asset('assets/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">
        <!-- Waves Effect Css -->
        <link href="{{ asset('assets/plugins/node-waves/waves.css') }}" rel="stylesheet" />
        <!-- Animation Css -->
        <link href="{{ asset('assets/plugins/animate-css/animate.css') }}" rel="stylesheet" />
        <!-- Morris Chart Css-->
        <link href="{{ asset('assets/plugins/morrisjs/morris.css') }}" rel="stylesheet" />
        <!-- Custom Css -->
        <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
        <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
        <link href="{{ asset('assets/css/themes/all-themes.css') }}" rel="stylesheet" />